# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import sys

# path to package root
sys.path.insert(0, os.path.abspath('../../'))  

project = 'Quartic B-Spline extension'
copyright = '2025, Florian Thaler'
author = 'Florian Thaler'
release = '2025'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',  # for Google-style docstrings
    'myst_parser',          # for Markdown
    'breathe'               # for docs generated by doxygen
]

myst_enable_extensions = [
    "dollarmath",     # enables $...$ and $$...$$ math
    "amsmath",        # optional, for advanced math commands
]

myst_dmath_double_inline = True         # for usage of $$ ... $$ in markdown files.

breathe_projects = {
    'quartic_bspline_cpp': '../build/xml'
}
breathe_default_project = 'quartic_bspline_cpp'

templates_path = ['_templates']
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

master_doc = 'index'